### ISSUE TITLE
Verzoek: Mac

### ISSUE THREAD

**Issue by richelbilderbeek** [maakplek/computerplek#2]
Er is een verzoek om Mac/`hackintosh` te installeren op de computers. Kan dat ook in praktijk?

**Comment by richelbilderbeek** [comment]
Ik begreep dat dit waarschijnlijk niet mogelijk is met onze hardware.

**Comment by yoyellow** [comment]
Niet met deze hardware, maar het zou wel een goedkope hackintosh kunnen zijn..

**Comment by richelbilderbeek** [comment]
Dus: op zoek gaan naar iemand die een hackintosh over heeft...

**Comment by HermanKopinga** [comment]
Of als we toch bezig zijn een Apple mac? Zolang 't intel hardware heeft met iig een core2duo en 2gb geheugen is het al potentieel waardevol voor ons.

**Comment by yoyellow** [comment]
Ja dat is natuurlijk nog mooier, maar ook moeilijker aan te komen..

**Comment by HermanKopinga** [comment]
Klopt, maar laten we niet puriteins alleen een Hackintosh zoeken :)
Kan die Xeon toren die er staat trouwens een hackintosh worden? Was ooit een behoorlijk beest.

**Comment by yoyellow** [comment]
Ik weet niet wat er in zit qua hardware, zal daar volgende week eens naar kijken wat er mogelijk is..

**Comment by richelbilderbeek** [comment]
Ik denk dat deze Issue nu wel dicht kan :+1:
